2019-10-26 14:51:57,527 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-10-26 14:52:00,289 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-10-28 21:14:01,555 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-10-28 21:27:18,823 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-11-04 21:18:03,679 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-11-04 21:18:22,075 ERROR: Exception on /edit_profile [GET] [in /home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/sean-paulmauro/oscars/app/routes.py", line 75, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile', form=form)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/sean-paulmauro/oscars/app/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/sean-paulmauro/oscars/app/templates/base.html", line 27, in top-level template code
    {% block content %}{% endblock %}
  File "/home/sean-paulmauro/oscars/app/templates/edit_profile.html", line 10, in block "content"
    {% for error in form.user.errors %}
  File "/home/sean-paulmauro/oscars/venv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.EditProfileForm object' has no attribute 'user'
2019-11-04 21:19:28,333 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-12-04 21:03:46,222 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-12-04 21:38:39,730 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-12-04 21:42:50,928 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
2019-12-26 11:45:41,460 INFO: Oscars startup [in /home/sean-paulmauro/oscars/app/__init__.py:39]
